//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewBatch
    {
        public string BatchNumber { get; set; }
        public string AcademicYrSemester { get; set; }
        public string ProgrammeID { get; set; }
        public Nullable<int> groupNumber { get; set; }
        public Nullable<int> subGroupNumber { get; set; }
        public string GroupID { get; set; }
        public string subGroupID { get; set; }
    }
}
