//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programme
    {
        public string ProgrammeID { get; set; }
        public string ProgrammeName { get; set; }
    }
}
