//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string RoomNumber { get; set; }
        public string BuildingNumber { get; set; }
        public byte[] RoomName { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
