//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public string OfferedYear { get; set; }
        public string OfferedSem { get; set; }
        public string SubName { get; set; }
        public string SubCode { get; set; }
        public Nullable<int> LecHours { get; set; }
        public Nullable<int> TuteHours { get; set; }
        public Nullable<int> LabHours { get; set; }
        public Nullable<int> EvaHours { get; set; }
    }
}
