//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMS2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public string Syear { get; set; }
        public string Ssemester { get; set; }
        public string Sname { get; set; }
        public byte[] Scode { get; set; }
        public Nullable<int> Lechour { get; set; }
        public Nullable<int> Tutehour { get; set; }
        public Nullable<int> Labhour { get; set; }
        public Nullable<int> Evhour { get; set; }
    }
}
